package local.csp.demo;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import net.datafaker.Faker;
import net.datafaker.service.RandomService;

import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Random;

public final class DatafakerDemoGenerator {
    private static final List<String> MAKES = List.of("Toyota", "Ford", "Volkswagen", "BMW", "Audi", "Skoda", "Volvo", "Mercedes-Benz");
    private static final List<String> MODELS = List.of("Corolla", "Focus", "Golf", "X3", "A4", "Octavia", "V60", "C-Class");
    private static final List<String> COLORS = List.of("white", "black", "silver", "blue", "gray", "red");
    private static final List<String> SERVICE_NAMES = List.of(
            "Brake system inspection",
            "Oil and filters service",
            "Timing belt replacement",
            "Suspension diagnostics",
            "AC service",
            "Battery and charging diagnostics"
    );
    private static final List<String> PART_NAMES = List.of(
            "Brake pads front axle",
            "Engine oil 5W-30",
            "Oil filter",
            "Air filter",
            "Timing belt kit",
            "Cabin filter",
            "Stabilizer link",
            "Battery 70Ah"
    );
    private static final List<String> STATUSES = List.of("new", "in_progress", "waiting_parts", "completed");

    public static void main(String[] args) throws IOException {
        Config config = Config.parse(args);
        Random random = new Random(config.seed);
        Faker faker = new Faker(Locale.forLanguageTag(config.locale), new RandomService(random));

        Map<String, Object> payload = new LinkedHashMap<>();
        payload.put("metadata", metadata(config));
        payload.put("users", users());
        payload.put("services", services());
        payload.put("suppliers", suppliers(faker, random));

        List<Map<String, Object>> customers = new ArrayList<>();
        List<Map<String, Object>> vehicles = new ArrayList<>();
        List<Map<String, Object>> repairs = new ArrayList<>();
        List<Map<String, Object>> purchases = new ArrayList<>();

        LocalDate anchor = LocalDate.of(2026, 4, 15);
        for (int i = 0; i < config.count; i++) {
            String suffix = String.format("%03d", i + 1);
            String customerKey = "customer-" + suffix;
            String vehicleKey = "vehicle-" + suffix;
            String repairKey = "repair-" + suffix;
            String status = STATUSES.get(random.nextInt(STATUSES.size()));
            LocalDate orderDate = anchor.minusDays(3L * i + random.nextInt(10));

            customers.add(mapOf(
                    "key", customerKey,
                    "full_name", faker.name().fullName(),
                    "phone", faker.phoneNumber().cellPhone(),
                    "email", faker.internet().emailAddress(),
                    "notes", "Generated by Datafaker for CSP demo data"
            ));

            vehicles.add(mapOf(
                    "key", vehicleKey,
                    "customer_key", customerKey,
                    "license_plate", licensePlate(random),
                    "make", MAKES.get(random.nextInt(MAKES.size())),
                    "model", MODELS.get(random.nextInt(MODELS.size())),
                    "year", 2014 + random.nextInt(12),
                    "vin", faker.vehicle().vin(),
                    "color", COLORS.get(random.nextInt(COLORS.size())),
                    "mileage", 35_000 + random.nextInt(190_000),
                    "last_service_date", orderDate.minusMonths(6).toString(),
                    "added_date", orderDate.minusYears(1).toString(),
                    "notes", "Generated vehicle from Datafaker scenario " + suffix
            ));

            String serviceName = SERVICE_NAMES.get(random.nextInt(SERVICE_NAMES.size()));
            repairs.add(mapOf(
                    "key", repairKey,
                    "vehicle_key", vehicleKey,
                    "master_email", "staff@autoservice.local",
                    "service_name", serviceName,
                    "service_line_keys", List.of(serviceKeyFor(serviceName)),
                    "issue_notes", faker.lorem().sentence(10),
                    "status", status,
                    "mileage_at_service", 36_000 + random.nextInt(190_000),
                    "estimated_date", orderDate.plusDays(4).toString(),
                    "completed_at", (status.equals("completed") ? orderDate.plusDays(5).toString() : null)
            ));

            int lineCount = 1 + random.nextInt(3);
            for (int line = 0; line < lineCount; line++) {
                String partName = PART_NAMES.get(random.nextInt(PART_NAMES.size()));
                BigDecimal purchasePrice = money(20 + random.nextInt(450), random);
                BigDecimal salePrice = purchasePrice.multiply(BigDecimal.valueOf(1.35)).setScale(2, RoundingMode.HALF_UP);
                purchases.add(mapOf(
                        "key", "purchase-" + suffix + "-" + (line + 1),
                        "supplier_key", "supplier-" + (1 + random.nextInt(3)),
                        "vehicle_key", vehicleKey,
                        "repair_key", repairKey,
                        "part_name", partName,
                        "quantity", 1 + random.nextInt(4),
                        "uom_code", "pcs",
                        "purchase_price", purchasePrice.toPlainString(),
                        "sale_price", salePrice.toPlainString(),
                        "order_date", orderDate.toString(),
                        "delivered", !status.equals("new"),
                        "is_shop_consumable", false,
                        "invoice_name", "DATAFAKER-DEMO-" + config.seed + "-" + suffix
                ));
            }
        }

        payload.put("customers", customers);
        payload.put("vehicles", vehicles);
        payload.put("repairs", repairs);
        payload.put("purchases", purchases);

        ObjectMapper mapper = new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);
        String json = mapper.writeValueAsString(payload) + "\n";
        if (config.output.equals("-")) {
            System.out.print(json);
        } else {
            Path output = Path.of(config.output);
            if (output.getParent() != null) {
                Files.createDirectories(output.getParent());
            }
            Files.writeString(output, json);
        }
    }

    private static Map<String, Object> metadata(Config config) {
        return mapOf(
                "generator", "datafaker",
                "schema_version", 1,
                "seed", config.seed,
                "locale", config.locale,
                "count", config.count,
                "profile", config.profile,
                "generated_at", OffsetDateTime.now(ZoneOffset.UTC).toString(),
                "marker", marker(config)
        );
    }

    private static List<Map<String, Object>> users() {
        return List.of(mapOf(
                "email", "staff@autoservice.local",
                "first_name", "Demo",
                "last_name", "Staff",
                "role", "staff",
                "is_staff", false,
                "password", "staff12345"
        ));
    }

    private static List<Map<String, Object>> services() {
        List<Map<String, Object>> rows = new ArrayList<>();
        for (String name : SERVICE_NAMES) {
            rows.add(mapOf(
                    "key", serviceKeyFor(name),
                    "name", name,
                    "description", "Generated by Datafaker demo generator",
                    "price", switch (name) {
                        case "Timing belt replacement" -> "720.00";
                        case "Suspension diagnostics" -> "180.00";
                        case "AC service" -> "240.00";
                        case "Battery and charging diagnostics" -> "160.00";
                        case "Brake system inspection" -> "220.00";
                        default -> "140.00";
                    },
                    "is_active", true
            ));
        }
        return rows;
    }

    private static List<Map<String, Object>> suppliers(Faker faker, Random random) {
        List<Map<String, Object>> rows = new ArrayList<>();
        for (int i = 1; i <= 3; i++) {
            rows.add(mapOf(
                    "key", "supplier-" + i,
                    "name", faker.company().name() + " Auto Parts",
                    "nip", String.valueOf(1_000_000_000L + Math.abs(random.nextLong() % 8_999_999_999L)),
                    "phone", faker.phoneNumber().phoneNumber(),
                    "email", faker.internet().emailAddress(),
                    "registered_address", faker.address().fullAddress(),
                    "notes", "Generated by Datafaker demo generator"
            ));
        }
        return rows;
    }

    private static String marker(Config config) {
        return "datafaker-demo:" + config.profile + ":" + config.seed;
    }

    private static String serviceKeyFor(String serviceName) {
        return serviceName.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+", "-").replaceAll("(^-|-$)", "");
    }

    private static String licensePlate(Random random) {
        return "DF " + (10000 + random.nextInt(90000));
    }

    private static BigDecimal money(int whole, Random random) {
        return BigDecimal.valueOf(whole * 100L + random.nextInt(100), 2);
    }

    private static Map<String, Object> mapOf(Object... args) {
        Map<String, Object> map = new LinkedHashMap<>();
        for (int i = 0; i < args.length; i += 2) {
            if (args[i + 1] != null) {
                map.put(String.valueOf(args[i]), args[i + 1]);
            }
        }
        return map;
    }

    private record Config(long seed, String locale, int count, String profile, String output) {
        static Config parse(String[] args) {
            if (args.length >= 2 && args[0].equals("generate") && args[1].equals("datafaker-demo")) {
                args = java.util.Arrays.copyOfRange(args, 2, args.length);
            } else if (args.length > 0 && !args[0].startsWith("-")) {
                throw new IllegalArgumentException("Unknown command. Expected: generate datafaker-demo");
            }
            long seed = 123L;
            String locale = "en-US";
            int count = 5;
            String profile = "small";
            String output = "build/datafaker-demo.json";
            for (int i = 0; i < args.length; i++) {
                String arg = args[i];
                String value = null;
                if (arg.contains("=")) {
                    String[] parts = arg.split("=", 2);
                    arg = parts[0];
                    value = parts[1];
                }
                switch (arg) {
                    case "--seed" -> {
                        if (value == null) i++;
                        seed = Long.parseLong(valueOrNext(value, args, i, "--seed"));
                    }
                    case "--locale" -> {
                        if (value == null) i++;
                        locale = valueOrNext(value, args, i, "--locale");
                    }
                    case "--count" -> {
                        if (value == null) i++;
                        count = Integer.parseInt(valueOrNext(value, args, i, "--count"));
                    }
                    case "--profile" -> {
                        if (value == null) i++;
                        profile = valueOrNext(value, args, i, "--profile");
                    }
                    case "--output" -> {
                        if (value == null) i++;
                        output = valueOrNext(value, args, i, "--output");
                    }
                    case "--help", "-h" -> printHelpAndExit();
                    default -> throw new IllegalArgumentException("Unknown argument: " + arg);
                }
            }
            if (count < 1) {
                throw new IllegalArgumentException("--count must be >= 1");
            }
            if (!List.of("small", "demo", "stress").contains(profile)) {
                throw new IllegalArgumentException("--profile must be one of: small, demo, stress");
            }
            return new Config(seed, locale, count, profile, output);
        }

        private static String valueOrNext(String inlineValue, String[] args, int index, String option) {
            if (inlineValue != null) {
                return inlineValue;
            }
            if (index >= args.length) {
                throw new IllegalArgumentException(option + " requires a value");
            }
            return args[index];
        }

        private static void printHelpAndExit() {
            System.out.println("Usage: csp-demo-data generate datafaker-demo --seed 123 --locale en-US --count 5 --profile small --output tmp/datafaker-demo.json");
            System.out.println("       csp-demo-data --seed 123 --locale en-US --count 5 --profile small --output tmp/datafaker-demo.json");
            System.exit(0);
        }
    }
}
